version: '2'
services:
  gemp-app:
    image: gemp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@gemp-oracle:1521:gemp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://gemp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://gemp-elasticsearch:9200
    ports:
      - 8080:8080
  gemp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: gemp-elasticsearch
